### ISSUE TITLE
Integrate into HoTT/HoTT

### ISSUE THREAD

**Issue by spitters** [SkySkimmer/HoTTClasses#3]
Since the introduction of IR is delayed, but there is a demand for math-classes in HoTT.
Would it be good to start merging the parts not depending on IR already?

**Comment by SkySkimmer** [comment]
The main question is what the code organisation should look like. Specifically I could rsync everything into the Algebra directory or some such thing but that seems disorganised somehow.
There may also be issues with conflicting notations, eg `+` for sum types vs for the addition operational typeclass (if we just say that disjoint sum is the addition on `Type` we get universes everywhere).

I'm also a bit concerned about the scope of HoTT, ie does HoTT have vocation to include every library based on it and if not what justifies the inclusion of a given library?

**Comment by spitters** [comment]
We should probably move the discussion here.
https://github.com/HoTT/HoTT/issues/884
